---
driver:
  name: vagrant
  customize:
    memory: 2048


driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1
  chef_omnibus_url: http://www.chef.io/chef/install.sh
  data_bags_path: ./databags

platforms:
  - name: chef/centos-6.6

    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 9090}]
      - ["forwarded_port", {guest: 8081, host: 9091}]
      - ["forwarded_port", {guest: 80, host: 9000}]
      - ["forwarded_port", {guest: 443, host: 9443}]
      - ["forwarded_port", {guest: 3306, host: 33060}]
      vm_hostname: false


suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    attributes: