---
driver:
  name: vagrant
  customize:
    memory: 2048

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6
    driver_config:
      vm_hostname: false


suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    attributes:
