name 'lamp'
maintainer 'JRT'
maintainer_email 'nfernal13@outlook.com'
license 'all_rights'
description 'Installs/Configures lamp'
long_description 'Installs/Configures lamp'
version '0.10.3
'

depends 'java'
depends 'maven'
depends 'mysql', '~> 6.0'
depends 'zip'
depends 'clamav'
depends 'openssl'
depends 'jenkins'
depends 'apache2'